export const DEFAULT = 'action/DEFAULT'

export const LEAGUE_ACTION = 'action/LEAGUE_ACTION'
export const LEAGUE_COMPLETE = 'action/LEAGUE_COMPLETE'

export const LEAGUE_DETAIL_ACTION = 'action/LEAGUE_DETAIL_ACTION'
export const LEAGUE_DETAIL_COMPLETE = 'action/LEAGUE_DETAIL_COMPLETE'

export const TRANSFER_LEAGUE_ACTION = 'action/TRANSFER_LEAGUE_ACTION'
export const TRANSFER_LEAGUE_COMPLETE = 'action/TRANSFER_LEAGUE_COMPLETE'

export const MATCHES_LEAGUE_ACTION = 'action/MATCHES_LEAGUE_ACTION'
export const MATCHES_LEAGUE_COMPLETE = 'action/MATCHES_LEAGUE_COMPLETE'

export const STATS_LEAGUE_ACTION = 'action/STATS_LEAGUE_ACTION'
export const STATS_LEAGUE_COMPLETE = 'action/STATS_LEAGUE_COMPLETE'